name: ServerRP
version: '${project.version}'
main: com.danikvitek.serverrp.Main
api-version: 1.16
authors: [ Danik_Vitek ]
description: Allows to set a single resource pack through all your servers using database

commands:
  resourcepack:
    aliases:
      - rp
    description: Set or get the resource pack of the server
    usage: "/resourcepack <upload <url> | get | link>"

permissions:
  serverrp.command.resourcepack.*:
    default: op
    children:
      - serverrp.command.resourcepack.upload
      - serverrp.command.resourcepack.get
      - serverrp.command.resourcepack.link
  serverrp.command.resourcepack.upload:
    default: op
    description: Set the resource pack of the server
  serverrp.command.resourcepack.get:
    default: true
    description: Get the resource pack of the server
  serverrp.command.resourcepack.link:
    default: true
    description: Get the link of the resource pack of the server